name: quickbills
description: A comprehensive Point of Sale (POS) and billing application for small to medium businesses.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^13.0.0

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  # Bluetooth Printing
  flutter_blue_plus: ^1.31.0
  esc_pos_utils: ^1.1.0
  # image: ^3.3.0  # Let esc_pos_utils determine the version

  # Database & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # API & Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2
  
  # File Management
  archive: ^3.4.9

  # Authentication
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7

  # Barcode
  mobile_scanner: ^3.5.2
  barcode_widget: ^2.0.4

  # PDF Generation
  pdf: ^3.8.4
  # printing: ^5.9.2  # Temporarily disabled due to namespace issue
  csv: ^5.1.1

  # Charts
  fl_chart: ^0.66.2

  # Utilities
  intl: ^0.18.1
  uuid: ^4.3.3
  share_plus: ^7.2.1
  url_launcher: ^6.2.3
  permission_handler: ^11.2.0
  file_picker: ^8.0.0
  excel: ^4.0.2

  # In-app purchases
  in_app_purchase: ^3.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.6
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700